# AnvilNote renderer Makefile
# A thin wrapper around pnpm so common workflows share one entry point.
# All comments are written in plain English without parentheses.

# Use pnpm as the package manager for every target.
PM := pnpm

# Forward optional CLI arguments to the renderer entrypoint.
ARGS ?=

# Provide sane local defaults for a smoke render when no args are given.
TMP_DIR := .tmp
DEV_INPUT := $(TMP_DIR)/dev-input.json
DEV_OUTPUT_DIR := $(TMP_DIR)/pdf
DEV_WORK_DIR := $(TMP_DIR)/work

# Treat these targets as commands rather than files on disk.
.PHONY: help install dev render build start lint typecheck check format clean reset

# Show this help message when make runs without a target.
.DEFAULT_GOAL := help

help: ## List all available targets with a short description
	@echo "AnvilNote renderer - available make targets:"
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "} {printf "  \033[1m%-12s\033[0m %s\n", $$1, $$2}'

install: ## Install all project dependencies from the lockfile
	$(PM) install

dev: ## Run the renderer CLI or a built-in smoke render when ARGS are omitted
	@if [ -n "$(ARGS)" ]; then \
		$(PM) dev -- $(ARGS); \
	else \
		mkdir -p "$(TMP_DIR)" "$(DEV_OUTPUT_DIR)" "$(DEV_WORK_DIR)"; \
		printf '%s\n' \
			'{' \
			'  "document": {' \
			'    "id": "dev-document",' \
			'    "title": "Renderer Smoke Test",' \
			'    "content": [' \
			'      {' \
			'        "id": "block-1",' \
			'        "type": "heading",' \
			'        "props": { "level": 1 },' \
			'        "content": [{ "type": "text", "text": "Renderer Smoke Test", "styles": {} }],' \
			'        "children": []' \
			'      },' \
			'      {' \
			'        "id": "block-2",' \
			'        "type": "paragraph",' \
			'        "props": {},' \
			'        "content": [{ "type": "text", "text": "This PDF was generated by make dev.", "styles": {} }],' \
			'        "children": []' \
			'      }' \
			'    ]' \
			'  },' \
			'  "template": {' \
			'    "id": "minimal-lecture",' \
			'    "fields": {' \
			'      "title": "Renderer Smoke Test",' \
			'      "author": "AnvilNote",' \
			'      "date": "2026-06-26"' \
			'    }' \
			'  },' \
			'  "options": {' \
			'    "format": "pdf"' \
			'  }' \
			'}' > "$(DEV_INPUT)"; \
		echo "Running renderer smoke test..."; \
		echo "Input:  $(DEV_INPUT)"; \
		echo "Output: $(DEV_OUTPUT_DIR)"; \
		echo "Work:   $(DEV_WORK_DIR)"; \
		$(PM) dev -- --input "$(DEV_INPUT)" --output-dir "$(DEV_OUTPUT_DIR)" --work-dir "$(DEV_WORK_DIR)"; \
	fi

render: ## Run the renderer CLI with explicit command line arguments
	@if [ -z "$(ARGS)" ]; then \
		echo "Usage: make render ARGS=\"--input <file.json> --output-dir <dir> --work-dir <dir>\""; \
		exit 1; \
	fi
	$(PM) render -- $(ARGS)

build: ## Compile the TypeScript source into dist
	$(PM) build

start: ## Run the compiled renderer CLI
	$(PM) start

lint: ## Run ESLint across the whole project
	$(PM) lint

typecheck: ## Run the TypeScript compiler in no-emit mode
	$(PM) exec tsc --noEmit

# Run linting and type checking together as a quick quality gate.
check: lint typecheck ## Run lint and typecheck in sequence

format: ## Format the source tree with Prettier
	$(PM) exec prettier --write .

clean: ## Remove build output and local caches
	rm -rf dist coverage *.tsbuildinfo

# Wipe installed dependencies on top of the normal clean step.
reset: clean ## Remove node_modules in addition to build output
	rm -rf node_modules
