#import "dev-document-b421ca2b-0060-437b-8b8a-a8267f20aa4d-template.typ": anvil-note

#set page(paper: "a4", margin: (x: 22mm, y: 24mm))
#set text(font: "New Computer Modern", size: 11pt)

#anvil-note(
  title: "Renderer Smoke Test",
  author: "AnvilNote",
  date: "2026-06-26",
  [
= Renderer Smoke Test

This PDF was generated by make dev.
  ],
)
